package luaj;

import android.content.Context;
import android.ext.Tools;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.nio.channels.FileChannel;
import luaj.lib.BaseLib;
import luaj.lib.DebugLib;
import luaj.lib.PackageLib;

/* compiled from: src */
/* loaded from: classes.dex */
public class Globals extends LuaTable {
    public luaj.lib.j g;
    public BaseLib i;
    public PackageLib j;
    public DebugLib k;
    public c l;
    public b m;
    public e n;
    public boolean a = true;
    public int b = 0;
    private String q = null;
    public long c = 0;
    public int d = 0;
    public PrintStream e = System.out;
    public PrintStream f = System.err;
    public LuaThread h = new LuaThread(this);
    private String r = null;

    public void a(String str) {
        if (str != null) {
            if (!str.equals(this.q)) {
                this.q = str;
            } else {
                return;
            }
        }
        this.b++;
        if (this.b >= 1024) {
            throw new o("Too many open files: " + this.b + "; last: " + str);
        }
    }

    public void a(long j) {
        this.c += j;
        if (this.c >= 1073741824) {
            Context e = Tools.e();
            throw new o("Too many write to files: " + Tools.a(e, this.c) + "; last: " + Tools.a(e, j));
        }
    }

    @Override // luaj.LuaValue
    public Globals c() {
        return this;
    }

    public LuaValue c_(String str) {
        try {
            InputStream c = this.g.c(str);
            String absolutePath = d(str).getAbsolutePath();
            LuaValue a = a(c, String.valueOf('@') + absolutePath, "bt", this);
            if (a instanceof LuaClosure) {
                ((LuaClosure) a).d = absolutePath;
                return a;
            }
            return a;
        } catch (Exception e) {
            return a("load " + str + ": " + e, e);
        }
    }

    public LuaValue a(InputStream inputStream, String str, String str2, LuaValue luaValue) {
        LuaValue a;
        try {
            try {
                try {
                    try {
                        a = this.l.a(a(inputStream, str, str2), str, luaValue);
                        try {
                            inputStream.close();
                        } catch (IOException e) {
                        }
                    } catch (EOFException e2) {
                        a = a("truncated precompiled chunk", e2);
                    }
                } catch (Exception e3) {
                    a = a("load " + str + ": " + e3, e3);
                    try {
                        inputStream.close();
                    } catch (IOException e4) {
                    }
                }
                return a;
            } catch (o e5) {
                throw e5;
            }
        } finally {
            try {
                inputStream.close();
            } catch (IOException e6) {
            }
        }
    }

    public al a(InputStream inputStream, String str, String str2) {
        d dVar;
        if (str2.indexOf(98) >= 0) {
            if (this.n == null) {
                f("No undumper.");
            }
            byte[] bArr = new byte[4];
            int read = inputStream.read(bArr);
            if (bArr[0] == f.c[0] && bArr[1] == f.c[1] && bArr[2] == f.c[2] && bArr[3] == f.c[3]) {
                al a = this.n.a(inputStream, str);
                if (inputStream instanceof luaj.lib.b) {
                    luaj.lib.b bVar = (luaj.lib.b) inputStream;
                    InputStream a2 = bVar.a();
                    if (a2 instanceof FileInputStream) {
                        long b = bVar.b();
                        if (b < ((FileInputStream) a2).getChannel().size()) {
                            a.C = (int) b;
                        }
                    }
                } else if (inputStream instanceof FileInputStream) {
                    FileChannel channel = ((FileInputStream) inputStream).getChannel();
                    long position = channel.position();
                    if (position < channel.size()) {
                        a.C = (int) position;
                    }
                }
                return a;
            } else if (read > 0) {
                d a3 = d.a(inputStream);
                a3.unread(bArr, 0, read);
                inputStream = a3;
            }
        }
        if (str2.indexOf(116) >= 0) {
            byte[] bArr2 = new byte["; --[=========[ Lua assembler file generated by GameGuardian ".length()];
            int read2 = inputStream.read(bArr2);
            if (read2 > 0) {
                dVar = d.a(inputStream);
                dVar.unread(bArr2, 0, read2);
            } else {
                dVar = inputStream;
            }
            if (new String(bArr2).equals("; --[=========[ Lua assembler file generated by GameGuardian ")) {
                try {
                    return new lasm.a(dVar).a();
                } catch (lasm.g e) {
                    throw new o("Failed assemble: " + e.getMessage(), e);
                }
            } else if (bArr2[0] == f.c[0] && bArr2[1] == f.c[1] && bArr2[2] == f.c[2] && bArr2[3] == f.c[3]) {
                throw new o("attempt to load a binary chunk (mode is '" + str2 + "')");
            } else {
                return a(dVar, str);
            }
        }
        throw new o("attempt to load a text chunk (mode is '" + str2 + "'");
    }

    public al a(InputStream inputStream, String str) {
        if (this.m == null) {
            f("No compiler.");
        }
        return this.m.a(d.a(inputStream).a(true), str);
    }

    public void c(String str) {
        this.r = str;
    }

    public File d(String str) {
        String str2 = this.r;
        return (str2 == null || (str.length() != 0 && str.charAt(0) == '/')) ? new File(str) : new File(str2, str);
    }
}
